config/routes.rb
Rails.application.routes.draw do
  root to: 'events#index'

  devise_for :users

  resources :events do
    resources :attendances, only: [:new, :create]
    resources :eventimages, only: [:create]
  end

  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  
  belongs_to :participant, class_name: 'User'
  belongs_to :event
  
  after_create :new_attendance_send

  def new_attendance_send
    UserMailer.new_attendance_email(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord

  validate :is_in_the_future?
  validate :is_multiple_of_5?
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :start_date, presence: true
  validates :duration, presence: true, numericality: { only_integer: true, greater_than: 0}
  validates :price, presence: true, numericality: { only_integer: true, less_than_or_equal_to: 1000 }
  validates :location, presence: true

  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :participants, through: :attendances
  has_one_attached :eventimage

  def end_date
    start_date + duration.minutes
  end

  def is_in_the_future?
    if start_date.present? && start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end

  def is_multiple_of_5?
    if duration.present? && duration % 5 != 0 && duration > 0
      errors.add(:duration, "must be a multiple of 5")
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :organized_events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'participant_id'
  has_one_attached :avatar

  after_create :welcome_send

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  include UsersHelper

  protected
  
  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :avatar)}
    devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :description, :email, :password, :password_confirmation, :current_password, :avatar)}
  end

end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @attendance = Attendance.new
    @event = Event.find(params[:event_id])
  end

  def create
    @event = Event.find(params[:event_id])
    @amount = @event.price * 100
    @attendance = Attendance.create(event_id: @event.id, participant_id: current_user.id, stripe_customer_id: current_user.id)

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Paiement évènement',
      currency: 'eur',
    })

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_event_attendance(@event.id)

  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @user.avatar.attach(params[:avatar])
    redirect_to(user_path(@user))
  end
end

app/controllers/eventimages_controller.rb
class EventimagesController < ApplicationController

  def create
    @event = Event.find(params[:event_id])
    @event.eventimage.attach(params[:eventimage])
    redirect_to(event_path(@event.id))
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :show]

  def index
    @events = Event.order(:start_date).all
  end

  def show
    @event = Event.find(params['id'])
    @attedance = Attendance.new
    @attendances = @event.attendances
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.admin = current_user
    @event.eventimage.attach(params[:eventimage])
    if @event.save
      redirect_to "/"
      flash[:success] = "L'événement a bien été créé !"
    else
      render :new
      flash[:danger] = "L'énévement n'a pas été créé !"
    end
  end

  def edit
    @event = Event.find(params['id'])
  end

  def update
    @event = Event.find(params['id'])
    if @event.update(event_params)
      redirect_to event_path(@event.id)
      flash[:success] = "L'événement a bien été édité !"
    else
      redirect_to edit_event_path(@event.id)
      flash[:danger] = "L'événement n'a pas été édité !"
    end
  end

  def destroy
    @user = current_user
    @event = Event.find(params['id'])
    if @event.destroy
      redirect_to user_path(@user.id)
      flash[:success] = "L'événement a bien été supprimé !"
    else
      render event_path(@event.id)
      flash[:danger] = "L'événement n'a pas été supprimé !"
    end
  end


  private

  def event_params
    params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:show]

  def show
    @user = User.find(params[:id])
    @events = Event.where(admin: current_user)
    @participations = Attendance.where(participant: current_user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/eventimages_helper.rb
module EventimagesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def is_admin
    @event = Event.find(params['id'])
    !current_user.nil? && current_user.id == @event.admin_id
  end

  def current_user_profil
    current_user.id.to_i == params[:id].to_i
  end

  def already_participant
    Attendance.find_by(event_id: @event.id, participant_id: current_user.id)
  end  

end

app/views/attendances/create.html.erb
<div class="card ml-5 mr-5 p-5 mt-5">
  <div class="card-header display-4 mt-4-auto mb-3 text-center">Tu es bien inscrit à l'événement : <%= @event.title %> !</div>
  <div class="text-center">Rends toi sur ton profil pour voir les détails</div>
  <div class="card-body d-flex justify-content-between mb-5">
    <div class="btn btn-outline-info role="button" aria-pressed="true" style="width:200px;"> <%= link_to "Ton profil", user_path(current_user.id) %></div>
    <div class="btn btn-outline-secondary" role="button" aria-pressed="true" style="width:200px;"> <%= link_to "Créer un event", new_event_path %></div>
    <div class="btn btn-outline-primary" role="button" aria-pressed="true" style="width:200px;"> <%= link_to "Liste des events", events_path %></div>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="card ml-5 mr-5 p-5 mt-5">
  <div class="card-header display-4 mt-4-auto mb-3 d-flex justify-content-between">Inscription</div>
  <div class="card-body">
    <div class="row">
      <div class="col-6">
          <h5 class="card-title mb-4">L'inscription sera validée dès que le paiement sera effectué !</h5>
          <p class="card-title">Récapitulatif de l'événement :</p>
          <p class="card-title">Titre : <%= @event.title.capitalize %></p>
          <p class="card-title">Adresse : <%= @event.location %></p>
          <p class="card-title">Débute le : <%= @event.start_date.strftime("%d/%m/%Y à %I:%M") %></p>
          <p class="card-title"></p>
          <em class="text-muted mb-3"></em>
      </div>
      <div class="col-3 offset-2 text-center pt-5">
          <%= form_tag url_for(action: 'create'), method: "post" do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
            <label class="amount">
              <p>Finaliser le paiement</p>
              <p>de <strong><%= @event.price %> €</strong></p>
            </label>
          </article>
          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="<%= "Inscription" %>"
                  data-currency="eur"
                  data-amount="<%= @amount %>"
                  data-locale="auto"></script>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/charges/_form.html.erb
              <%= form_tag attendance_charges_path(@event.id) do %>
                <article>
                  <% if flash[:error].present? %>
                    <div id="error_explanation">
                      <p><%= flash[:error] %></p>
                    </div>
                  <% end %>
                  <label class="amount">
                  <p>Pour rejoindre cet évévement, merci de payer :</p>
                    <strong><%= @event.price %> €</strong>
                  </label>
                </article>
                <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                        data-description="Inscription"
                        data-amount="<%= @event.price * 100 %>"
                        data-currency="eur"
                        data-locale="auto"></script>
                <% end %>
             

app/views/events/edit.html.erb
<div class="masthead pt-5 mb-5">
  <div class="container">
    <h1 class="display-3 masthead-text mt-5">Edition de <%= @event.title.capitalize%><h1>
  </div>
</div>

<div class="card ml-5 mr-5 p-5 mt-5">
  <%= form_for(@event, as: :event, url: event_path(@event), method: :patch, html: { class: "edit_event", id: "edit_event.id" }, multipart: true) do |f|  %>

      <div class="field">
        <%= f.label :eventimage, "Choisis une image" ,class: "col-md-4 control-label"%>
        <%= f.file_field :eventimage, class:"col-md-6 form-control mb-4"%>
      </div>

      <div class="field">
        <%= f.label :title, "Comment s'appelle ton événement" ,class: "col-md-4 control-label"%><small class="text-muted">(entre 5 et 140 caractères)</small>
        <%= f.text_field :title, class:"col-md-6 form-control mb-4" %>
      </div>

      <div class="field">
        <%= f.label :description, "Ça parle de quoi ?", class: "col-md-4 control-label" %><small class="text-muted">(entre 20 et 1000 caractères)</small>
        <%= f.text_area :description, class:"col-md-6 form-control mb-4" %>
      </div>

      <div class="field">
        <%= f.label :location, "Ça se passe où ?", class: "col-md-4 control-label" %>
        <%= f.text_field :location, class:"col-md-6 form-control mb-4" %>
      </div>

        <div class="field">
          <%= f.label :start_date, "Ça commence quand ?", class: "col-md-3 control-label" %>
          <%= f.datetime_local_field :start_date, class: 'form-control', value: Time.now.localtime.strftime("%Y-%m-%dT%H:%M"), class:"col-md-6 form-control mb-4"  %>

        </div>

        <div class="field">
          <%= f.label :duration, "Ça dure combien de temps ?", class: "col-md-5 control-label" %><small class="text-muted">(en minutes)</small>
          <%= f.number_field :duration, min: 5, step: 5, class:"col-md-6 form-control mb-4"  %>
        </div>

        <div class="field">
          <%= f.label :price, "Ça coûte combien ?", class: "col-md-5 control-label" %>
          <%= f.number_field :price, in: 0..1000, step: 1, class:"col-md-6 form-control mb-4"%>
        </div>

      <div class="actions">
        <%= f.submit "Editer", class:"btn btn-outline-secondary nav-link btn-sub" %>
      </div>
  <% end %>
</div>

app/views/events/index.html.erb
<div class="masthead pt-5 mb-5">
  <div class="container">
    <h1 class="display-3 masthead-text mt-5">Créer ou trouver un événement ?</h1>
    <p class="masthead-text">Ce site est fait pour toi ! Crée des évévements dans ta ville ou trouve des trucs trop cool à faire !</p>
    <%= link_to "Créer un event", new_event_path, class:"nav-link btn btn-masthead", role:"button", aria_pressed:"true" %>
  </div>
</div>

<div class="container">
  <div class="album ">
    <div class="container">
      <div class="row">
        <% @events.each do |event| %>
          <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
              <% if event.eventimage.attached? %>
                <img class="bd-placeholder-img card-img-top" width="100%" height="225"><%= image_tag event.eventimage %></img>
              <% else %>
                <img class="bd-placeholder-img card-img-top" width="100%" height="225"></img>
              <% end %>
              <div class="card-body card-event">
                <h2 class="card-text"><%= event.title.capitalize %></h2>
                <p class="card-text"><%= event.description %></p>
                <em class="card-text">Prévu le <%= event.start_date.strftime("%d/%m/%Y")%></em></br>
                <% if event.price == 0 %>
                  <p class="mt-3"><strong>C'est gratuit !</strong></p>
                <% else %>
                  <p class="mt-3">Participation de <strong><%= event.price %> €</strong></p>
                <% end %>
                <div class="d-flex justify-content-between align-items-center mt-3">
                  <div class="btn-group">
                    <%= link_to "Voir", event_path(event.id), class:"btn btn-outline-secondary nav-link btn-card", type:"button"%>
                  </div>
                  <small class="text-muted"><td><%= event.attendances.count %> inscrits</td></small>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="masthead pt-5 mb-5">
  <div class="container">
    <h1 class="display-3 masthead-text mt-5">Crée ton événement<h1>
  </div>
</div>

<div class="card m-5 p-5">
  <%= form_for(@event, as: :event, url: events_path(@event), method: :post, html: { class: "new_event"}, multipart: true) do |f|  %>

      <div class="field">
        <%= f.label :eventimage, "Choisis une image" ,class: "col-md-4 control-label"%>
        <%= f.file_field :eventimage, class:"col-md-6 form-control mb-4"%>
      </div>

      <div class="field">
        <%= f.label :title, "Comment s'appelle ton événement" ,class: "col-md-4 control-label"%><small class="text-muted">(entre 5 et 140 caractères)</small>
        <%= f.text_field :title, class:"col-md-6 form-control mb-4", required: true %>
      </div>

      <div class="field">
        <%= f.label :description, "Ça parle de quoi ?", class: "col-md-4 control-label" %><small class="text-muted">(entre 20 et 1000 caractères)</small>
        <%= f.text_area :description, class:"col-md-6 form-control mb-4"%>
      </div>

      <div class="field">
        <%= f.label :location, "Ça se passe où ?", class: "col-md-4 control-label" %>
        <%= f.text_field :location, class:"col-md-6 form-control mb-4", required: true %>
      </div>

        <div class="field">
          <%= f.label :start_date, "Ça commence quand ?", class: "col-md-3 control-label" %>
          <%= f.datetime_local_field :start_date, class: 'form-control', value: Time.now.localtime.strftime("%Y-%m-%dT%H:%M"), class:"col-md-6 form-control mb-4", required: true  %>
        </div>

        <div class="field">
          <%= f.label :duration, "Ça dure combien de temps ?", class: "col-md-5 control-label" %><small class="text-muted">(en minutes)</small>
          <%= f.number_field :duration, min: 5, step: 5, class:"col-md-6 form-control mb-4", required: true %>
        </div>

        <div class="field">
          <%= f.label :price, "Ça coûte combien ?", class: "col-md-5 control-label" %>
          <%= f.number_field :price, in: 0..1000, step: 1, class:"col-md-6 form-control mb-4", required: true %>
        </div>

      <div class="actions">
        <%= f.submit "Création", class:"btn btn-outline-secondary nav-link btn-sub" %>
      </div>
<% end %>
</div>

app/views/events/show.html.erb
<div class="masthead pt-5 mb-5">
  <div class="container">
    <h1 class="display-3 masthead-text mt-5"><%= @event.title.capitalize%><h1>
  </div>
</div>

<div class="card ml-5 mr-5 p-5 mt-5">
  <div class="card-body">
    <div class="row ml-5">
      <div class="col-5 p-2">
        <h5 class="card-title mb-4"><%= @event.description %></h5>
        <p class="card-title">Prévu pour le <strong><%= @event.start_date.strftime("%d/%m/%Y à %I:%M") %></p></strong>
        <p class="card-title">Termine le <strong><%= @event.end_date.strftime("%d/%m/%Y à %I:%M") %></p></strong>
        <p class="card-title">Ça se passe au <strong><%= @event.location %></p></strong>
        <p class="card-title">Evénement créé par <strong><%=link_to @event.admin.first_name + " " + @event.admin.last_name, user_path(@event.admin.id)%></p></strong>
        <em class="text-muted mb-3">Il y a <%= @attendances.count %> personne(s) inscrite(s)</em>
      </div>
      <div class="col-6  ml-5 mt-5 text-center">
        <% if is_admin %>
          <%= link_to "Editer", edit_event_path(@event.id), class:"btn btn-outline-info mt-3 mb-3 mr-3" %>
          <%= link_to 'Supprimer', event_path(@event.id), method: :delete, data: { confirm: 'Es-tu sûr ?' }, class:"btn btn-outline-danger mt-3 mb-3 mr-3" %>
        <% elsif @event.price == 0 %>
          <p class="mt-3"><strong>C'est gratuit !</strong></p>
        <% elsif already_participant %>
          <div class="col-8 ml-5 mt-5 text-center">Tu participes déjà à cet événement ! Tu peux le suivre sur ton profil ou découvrir les autres !</div>
          <div class="btn btn-outline-info mt-3 mb-3 mr-3" role="button" aria-pressed="true"> <%= link_to "Liste des events", events_path %></div>
          <div class="btn btn-outline-primary mt-3 mb-3 mr-3" role="button" aria-pressed="true"> <%= link_to 'Mon profil', user_path(current_user) %></div>
        <% elsif user_signed_in? %>
          <%= link_to "Inscris toi ici", new_event_attendance_path(@event.id), class:"nav-link col-8 ml-5 mt-5 text-center btn btn-outline-info btn-sub"%>
        <% else %>
          <div class="col-8 ml-5 mt-5 text-center">Pour participer à cet évévement, tu dois te <%= link_to "connecter", new_user_session_path %> ou <%= link_to "créer un compte", new_user_registration_path%>.</div>
        <% end %>
      </div>
    </div>
    <% if is_admin %>
      <hr>
      <div class="card-header display-4 mt-4-auto mb-3 card-header-show">Liste des personnes inscrites</div>
      <% if @attendances.count != 0 %>
        <div class="row mt-3 ml-3">
          <% @attendances.each do |attendance| %>
            <div class="col-lg-4">
              <svg class="bd-placeholder-img rounded-circle" width="140" height="140" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 140x140"><title>Placeholder</title><rect width="100%" height="100%" fill="#777"/><text x="50%" y="50%" fill="#777" dy=".3em">140x140</text></svg>
              <h2><%= attendance.participant.first_name%> <%= attendance.participant.last_name%></h2>
              <p><%= link_to attendance.participant.email, "mailto:"+attendance.participant.email %></p>
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventbriteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Pacifico|Raleway&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Dancing+Script|Pacifico|Raleway&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/7fbc2f72d3.js" crossorigin="anonymous"></script>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg d-flex justify-content-between">
      <div class="container">
        <%= link_to 'Find an Event', root_path, class: 'navbar-brand' %>
      </div>
      <div class="container d-flex justify-content-end mt-1">
          <ul class="navbar-nav">
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Créer un event", new_event_path, class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Mon profil", user_path(current_user), class:"nav-link"%>
              </li>
              <li class="nav-item">
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class:"nav-link" %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "S'inscrire", new_user_registration_path, class:"nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Se connecter", new_user_session_path, class:"nav-link" %>
              </li>
            <% end %>
          </ul>
        </div>
    </nav>

    <main>
      <div class="errors">
        <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>"><%= msg %></div>
        <% end %>
      </div>

      <%= yield %>
    </main>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>

</html>

app/views/users/show.html.erb
<div class="container">
  <div class="card ml-5 mr-5 p-5 mt-5">
    <div class="card-header display-4 mt-4-auto mb-3 row d-flex justify-content-between align-items-center">
      <div><%= @user.first_name %> <%= @user.last_name %></div>
      <% if @user.avatar.attached? %>
        <div><%= image_tag @user.avatar.variant(resize: "150x150!") %></div>
      <% end %>
    </div>
      <div class="card-body">
        <h5 class="card-title"><%= @user.description %></h5>
        <em class="card-title"><%= @user.email %></em></br>
        <% if current_user_profil %>
           <div class="btn btn-outline-primary mt-3 mb-3 mr-3" role="button" aria-pressed="true"> <%= link_to "Créer un évévement", new_event_path %></div>
          <div class="btn btn-outline-info mt-3 mb-3 mr-3" role="button" aria-pressed="true"> <%= link_to "Modifier ton profil", edit_user_registration_path(current_user) %></div>
        </div>
      </div>
    </div>
    <div class="row ml-3 ">
      <div class="col-7 ml-5 mt-5">
      <h4 class="font-italic">Tes événements</h4> 
        <% @events.all.each do |event| %>
          <div class="card mb-4 mt-3 shadow-sm">
            <div class="card-body">
              <h2 class="card-text"><%= event.title %></h2>
              <p class="card-text"><%= event.description %></p>
              <em class="card-text">Prévu pour le <%= event.start_date.strftime("%d/%m/%Y à %I:%M") %></em>
              <div class="d-flex justify-content-between align-items-center mt-3">
                <button type="button" class="btn btn-sm btn-outline-secondary"><%= link_to "Voir", event_path(event.id)%></button>
                <small class="text-muted"><td><%= event.attendances.count %> inscrits</td></small>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <aside class="col-3 ml-5 mt-5 blog-sidebar">
        <h4 class="font-italic">Tes participations</h4> 
          <ol class="list-unstyled mb-0">
            <% @participations.all.each do |participation| %>
              <li class="card-text mt-3"><%= link_to participation.event.title.capitalize, event_path(participation.event.id) %> le <%= participation.event.start_date.strftime("%d/%m/%Y") %></li>
            <% end %>
          </ol>
      </aside>
    </div>
  <% end %>
</div>